# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nornsctl < Formula
  desc "CLI for the Norns durable agent runtime"
  homepage "https://github.com/amackera/nornsctl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amackera/nornsctl/releases/download/v0.2.0/nornsctl_darwin_amd64.tar.gz"
      sha256 "6e2e8b6feb90f05253f2f655fa7e541aa866211cf2e3a8abf05864a4e79ecda8"

      define_method(:install) do
        bin.install "nornsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amackera/nornsctl/releases/download/v0.2.0/nornsctl_darwin_arm64.tar.gz"
      sha256 "0db067d5302d11a57c3ce46e0f732d7892cc5c1b33e909b92304b76c83b5b63c"

      define_method(:install) do
        bin.install "nornsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amackera/nornsctl/releases/download/v0.2.0/nornsctl_linux_amd64.tar.gz"
      sha256 "88740d001f5bda8cc95bd7968c93da2e98e822d4f9845287615aaa15328b1bd0"
      define_method(:install) do
        bin.install "nornsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amackera/nornsctl/releases/download/v0.2.0/nornsctl_linux_arm64.tar.gz"
      sha256 "91fd47f82767fad01bef0a975c57acb858dd9e614bd7607d5814e44353ad49ee"
      define_method(:install) do
        bin.install "nornsctl"
      end
    end
  end
end
